package com.elitecouture.app.data.remote

import com.elitecouture.app.domain.model.Product
import io.github.jan.supabase.postgrest.from
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import java.util.UUID

/**
 * Supabase service for product operations (CRUD).
 * 
 * This service handles all product-related operations with Supabase PostgreSQL,
 * replacing the local SQLite implementation.
 */
object SupabaseProductService {
    
    /**
     * Data class representing the product table schema in Supabase.
     * 
     * Note: PostgreSQL features used:
     * - `images` and `tags` are TEXT[] arrays (not pipe-separated strings)
     * - `created_at` is auto-generated by database
     */
    @Serializable
    data class ProductDto(
        val id: Long? = null,
        val uuid: String = UUID.randomUUID().toString(),
        val name: String,
        val type: String? = null,
        val gender: String? = null,
        val description: String? = null,
        val price: Double,
        val stock: Int = 0,
        val images: List<String> = emptyList(),
        val tags: List<String> = emptyList(),
        val is_visible_to_guest: Boolean = true,
        val created_at: Long? = null
    )
    
    /**
     * Converts domain model to DTO for Supabase operations.
     */
    private fun Product.toDto(): ProductDto = ProductDto(
        id = if (id == 0L) null else id,
        uuid = uuid,
        name = name,
        type = type,
        gender = gender,
        description = description,
        price = price,
        stock = stock,
        images = images,
        tags = tags,
        is_visible_to_guest = isVisibleToGuest
    )
    
    /**
     * Converts DTO to domain model.
     */
    private fun ProductDto.toDomain(): Product = Product(
        id = id ?: 0L,
        uuid = uuid,
        name = name,
        type = type,
        gender = gender,
        description = description,
        price = price,
        stock = stock,
        images = images,
        tags = tags,
        isVisibleToGuest = is_visible_to_guest
    )
    
    // ======================================================================
    // CREATE
    // ======================================================================
    
    /**
     * Creates a new product in Supabase.
     * 
     * @param product Product domain model
     * @return The created product with server-generated ID
     * @throws Exception if creation fails
     */
    suspend fun createProduct(product: Product): Product = withContext(Dispatchers.IO) {
        val dto = product.toDto()
        val result = SupabaseClientProvider.client
            .from("products")
            .insert(dto) {
                select()
            }
            .decodeSingle<ProductDto>()
        
        result.toDomain()
    }
    
    /**
     * Creates multiple products in a single batch operation.
     * 
     * @param products List of products to create
     * @return List of created products with server-generated IDs
     * @throws Exception if creation fails
     */
    suspend fun createProducts(products: List<Product>): List<Product> = withContext(Dispatchers.IO) {
        val dtos = products.map { it.toDto() }
        val results = SupabaseClientProvider.client
            .from("products")
            .insert(dtos) {
                select()
            }
            .decodeList<ProductDto>()
        
        results.map { it.toDomain() }
    }
    
    // ======================================================================
    // READ
    // ======================================================================
    
    /**
     * Retrieves a product by UUID.
     * 
     * @param uuid Product UUID
     * @return Product if found, null otherwise
     */
    suspend fun getProductByUuid(uuid: String): Product? = withContext(Dispatchers.IO) {
        try {
            val result = SupabaseClientProvider.client
                .from("products")
                .select {
                    filter {
                        eq("uuid", uuid)
                    }
                }
                .decodeSingle<ProductDto>()
            
            result.toDomain()
        } catch (e: Exception) {
            null
        }
    }
    
    /**
     * Retrieves all products from catalog.
     * 
     * @param includeGuestHidden If true, includes products not visible to guests
     * @return List of products
     */
    suspend fun getAllProducts(includeGuestHidden: Boolean = false): List<Product> = withContext(Dispatchers.IO) {
        val results = if (includeGuestHidden) {
            SupabaseClientProvider.client
                .from("products")
                .select()
                .decodeList<ProductDto>()
        } else {
            SupabaseClientProvider.client
                .from("products")
                .select {
                    filter {
                        eq("is_visible_to_guest", true)
                    }
                }
                .decodeList<ProductDto>()
        }
        
        results.map { it.toDomain() }
    }
    
    /**
     * Searches products by name (case-insensitive).
     * 
     * @param query Search query
     * @return List of matching products
     */
    suspend fun searchProducts(query: String): List<Product> = withContext(Dispatchers.IO) {
        val results = SupabaseClientProvider.client
            .from("products")
            .select {
                filter {
                    ilike("name", "%$query%")
                }
            }
            .decodeList<ProductDto>()
        
        results.map { it.toDomain() }
    }
    
    /**
     * Filters products by type and/or gender.
     * 
     * @param type Product type (e.g., "Vestido", "Camisa")
     * @param gender Product gender (e.g., "Hombre", "Mujer")
     * @return List of matching products
     */
    suspend fun filterProducts(type: String? = null, gender: String? = null): List<Product> = withContext(Dispatchers.IO) {
        val results = SupabaseClientProvider.client
            .from("products")
            .select {
                filter {
                    if (type != null) eq("type", type)
                    if (gender != null) eq("gender", gender)
                }
            }
            .decodeList<ProductDto>()
        
        results.map { it.toDomain() }
    }
    
    // ======================================================================
    // UPDATE
    // ======================================================================
    
    /**
     * Updates an existing product.
     * 
     * @param product Product with updated data (must have valid UUID)
     * @return Updated product
     * @throws Exception if update fails
     */
    suspend fun updateProduct(product: Product): Product = withContext(Dispatchers.IO) {
        val dto = product.toDto()
        SupabaseClientProvider.client
            .from("products")
            .update(
                mapOf(
                    "name" to dto.name,
                    "type" to dto.type,
                    "gender" to dto.gender,
                    "description" to dto.description,
                    "price" to dto.price,
                    "stock" to dto.stock,
                    "images" to dto.images,
                    "tags" to dto.tags,
                    "is_visible_to_guest" to dto.is_visible_to_guest
                )
            ) {
                filter {
                    eq("uuid", product.uuid)
                }
            }
        
        product
    }
    
    /**
     * Updates product stock.
     * 
     * @param uuid Product UUID
     * @param newStock New stock quantity
     * @throws Exception if update fails
     */
    suspend fun updateStock(uuid: String, newStock: Int) = withContext(Dispatchers.IO) {
        SupabaseClientProvider.client
            .from("products")
            .update(
                mapOf("stock" to newStock)
            ) {
                filter {
                    eq("uuid", uuid)
                }
            }
    }
    
    // ======================================================================
    // DELETE
    // ======================================================================
    
    /**
     * Deletes a product by UUID.
     * 
     * @param uuid Product UUID
     * @throws Exception if deletion fails
     */
    suspend fun deleteProduct(uuid: String) = withContext(Dispatchers.IO) {
        SupabaseClientProvider.client
            .from("products")
            .delete {
                filter {
                    eq("uuid", uuid)
                }
            }
    }
    
    /**
     * Deletes all products (for testing only).
     * 
     * ⚠️ WARNING: This will delete ALL products in the database!
     */
    suspend fun deleteAllProducts() = withContext(Dispatchers.IO) {
        SupabaseClientProvider.client
            .from("products")
            .delete {
                // No filter = delete all
            }
    }
}
